/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bitwars;

import java.io.IOException;
import java.io.OutputStream;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.UIManager;

/**
 *
 * @author lyx
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        this.setTitle("比特大战 by刘琰翔");

        strategyMap = new HashMap<String, String>();
        strategyList = new ArrayList<Strategy>();
        classList = new ArrayList<Object>();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultArea = new javax.swing.JTextArea();
        jLabelLookStrategy = new javax.swing.JLabel();
        jComboBoxStrategy = new javax.swing.JComboBox();
        jLabelResultArea = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaLookStrategyArea = new javax.swing.JTextArea();
        jButtonAddStrategy = new javax.swing.JButton();
        jButtonStartWar = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabelRound = new javax.swing.JLabel();
        jTextRound = new javax.swing.JTextField();
        jButtonEditStrategy = new javax.swing.JButton();
        jButtonDeteleStrategy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextAreaResultArea.setEditable(false);
        jTextAreaResultArea.setColumns(20);
        jTextAreaResultArea.setRows(5);
        jScrollPane1.setViewportView(jTextAreaResultArea);

        jLabelLookStrategy.setText("策略查看：");

        jComboBoxStrategy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxStrategyItemStateChanged(evt);
            }
        });

        jLabelResultArea.setText("大战结果：");

        jTextAreaLookStrategyArea.setEditable(false);
        jTextAreaLookStrategyArea.setColumns(20);
        jTextAreaLookStrategyArea.setRows(5);
        jScrollPane2.setViewportView(jTextAreaLookStrategyArea);

        jButtonAddStrategy.setText("新增策略");
        jButtonAddStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStrategyActionPerformed(evt);
            }
        });

        jButtonStartWar.setText("执行");
        jButtonStartWar.setEnabled(false);
        jButtonStartWar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartWarActionPerformed(evt);
            }
        });

        jButtonExit.setText("退出");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelRound.setText("大战回合：");

        jButtonEditStrategy.setText("编辑策略");
        jButtonEditStrategy.setEnabled(false);
        jButtonEditStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditStrategyActionPerformed(evt);
            }
        });

        jButtonDeteleStrategy.setText("删除策略");
        jButtonDeteleStrategy.setEnabled(false);
        jButtonDeteleStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeteleStrategyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRound)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextRound, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelLookStrategy)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxStrategy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAddStrategy)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonEditStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelResultArea)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDeteleStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonStartWar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLookStrategy)
                    .addComponent(jComboBoxStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelResultArea))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRound)
                    .addComponent(jTextRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStartWar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeteleStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonAddStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStrategyActionPerformed
        addFrame = new AddStrategyJFrame(this);
        addFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAddStrategyActionPerformed

    private void jComboBoxStrategyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxStrategyItemStateChanged
        if (jComboBoxStrategy.getSelectedItem() == null) {
            return;
        }
        jTextAreaLookStrategyArea.setText(strategyMap.get(jComboBoxStrategy.getSelectedItem().toString()));
    }//GEN-LAST:event_jComboBoxStrategyItemStateChanged

    private void jButtonStartWarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartWarActionPerformed
        if ("".equals(jTextRound.getText())) {
            JOptionPane.showMessageDialog(this, "请输入要对决的回合数！");
            return;
        }
        int round = Integer.valueOf(jTextRound.getText());
        int[][] scoreTable = {{1, 5}, {0, 3}};
        if (round < 1) {
            JOptionPane.showMessageDialog(this, "回合数不能小于1");
            return;
        }
        strategyList.clear();
        for (int i = 0; i < jComboBoxStrategy.getItemCount(); i++) {
            strategyList.add(new Strategy(jComboBoxStrategy.getItemAt(i).toString(), 0));
        }

        //开始比赛
        for (int i = 0; i < classList.size(); i++) {
            Integer[] A = new Integer[round + 1];
            Integer[] B = new Integer[round + 1];
            for (int j = i + 1; j < classList.size(); j++) {
                try {
                    for (int currentRound = 1; currentRound <= round; currentRound++) {
                        A[currentRound] = (int) classList.get(i).getClass().getMethod("decision", Integer.class,
                                Integer[].class, Integer[].class).invoke(classList.get(i), currentRound, A, B);
                        B[currentRound] = (int) classList.get(j).getClass().getMethod("decision", Integer.class,
                                Integer[].class, Integer[].class).invoke(classList.get(j), currentRound, B, A);
                        strategyList.get(i).addScore(scoreTable[A[currentRound]][B[currentRound]]);
                        strategyList.get(j).addScore(scoreTable[B[currentRound]][A[currentRound]]);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "大战出错，请重启程序！");
                    return;
                }
            }
        }

        Collections.sort(strategyList);
        jTextAreaResultArea.setText("各策略两两对战" + round + "轮\n各策略得分如下：\n");
        for (int i = 0; i < strategyList.size(); i++) {
            jTextAreaResultArea.append(String.valueOf(i+1) + ". " + strategyList.get(i).getName()
                    + "  得分： " + String.valueOf(strategyList.get(i).getScore())
                    + "\n");
        }

    }//GEN-LAST:event_jButtonStartWarActionPerformed

    private void jButtonEditStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditStrategyActionPerformed
        new EditStrategyJFrame(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEditStrategyActionPerformed

    private void jButtonDeteleStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeteleStrategyActionPerformed
        this.classList.remove(this.jComboBoxStrategy.getSelectedIndex());
        this.strategyMap.remove(this.jComboBoxStrategy.getSelectedItem().toString());
        this.jComboBoxStrategy.removeItemAt(this.jComboBoxStrategy.getSelectedIndex());

        if (this.jComboBoxStrategy.getItemCount() < 1) {
            this.jButtonDeteleStrategy.setEnabled(false);
            this.jButtonEditStrategy.setEnabled(false);
            this.jTextAreaLookStrategyArea.setText("");
        } else if (this.jComboBoxStrategy.getItemCount() < 2) {
            this.jButtonStartWar.setEnabled(false);
        } else {
            this.jTextAreaLookStrategyArea.setText(this.strategyMap.get(this.jComboBoxStrategy.getSelectedItem().toString()));
        }
    }//GEN-LAST:event_jButtonDeteleStrategyActionPerformed

    public Map<String, String> getStrategyMap() {
        return strategyMap;
    }

    public JComboBox getjComboBoxStrategy() {
        return jComboBoxStrategy;
    }

    public JTextArea getjTextAreaLookStrategyArea() {
        return jTextAreaLookStrategyArea;
    }

    public JButton getjButtonStartWar() {
        return jButtonStartWar;
    }

    public List<Object> getClassList() {
        return classList;
    }

    public void setClassList(List<Object> classList) {
        this.classList = classList;
    }

    public JButton getjButtonEditStrategy() {
        return jButtonEditStrategy;
    }

    public JButton getjButtonDeteleStrategy() {
        return jButtonDeteleStrategy;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddStrategy;
    private javax.swing.JButton jButtonDeteleStrategy;
    private javax.swing.JButton jButtonEditStrategy;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonStartWar;
    private javax.swing.JComboBox jComboBoxStrategy;
    private javax.swing.JLabel jLabelLookStrategy;
    private javax.swing.JLabel jLabelResultArea;
    private javax.swing.JLabel jLabelRound;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaLookStrategyArea;
    private javax.swing.JTextArea jTextAreaResultArea;
    private javax.swing.JTextField jTextRound;
    // End of variables declaration//GEN-END:variables
    private Map<String, String> strategyMap;
    private AddStrategyJFrame addFrame;
    private List<Strategy> strategyList;
    private List<Object> classList;
}
